In [16]:
#生成一個等差數列，首數為0，尾數為20，公差為1的數列。
import numpy as np
b = np.arange(20)
print(b)

#呈上題，將以上數列取出偶數。
b = np.arange(0,20,2)
print(b)

#呈1題，將數列取出3的倍數。
b = np.arange(0,20,3)
print(b)

#[簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
b = np.arange(20)
print('list(b): ', list(b))
print('b.tolist()',b.tolist())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18]
list(b):  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
b.tolist() [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [20]:
#[簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
c = np.arange(15).reshape([3,5])
print('list(c): ', list(c))
print('c.tolist()',c.tolist())
print('答:畫面看起來不一樣')

list(c):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
c.tolist() [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
答:畫面看起來不一樣


In [33]:
#請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）
a = np.array([0,1,2,3,4,5])
b = np.arange(6).reshape([2,3])
c = np.arange(24).reshape([2,3,4])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)
print("_____________")
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(b.data)
print("_____________")
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(c.data)

[0 1 2 3 4 5]
1
(6,)
6
int32
4
_____________
[[0 1 2]
 [3 4 5]]
2
(2, 3)
6
int32
4
_____________
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
(2, 3, 4)
24
int32
4


In [34]:
#如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 
print(a.tolist())
print(list(a))

b = np.random.randint(10, size=(3,4)) 
print(b.tolist())
print(list(b))

c = np.random.randint(10, size=(2,3,2)) 
print(c.tolist())
print(list(c))

[0, 5, 2, 0, 3, 6]
[0, 5, 2, 0, 3, 6]
[[4, 1, 4, 7], [2, 5, 8, 8], [5, 4, 0, 9]]
[array([4, 1, 4, 7]), array([2, 5, 8, 8]), array([5, 4, 0, 9])]
[[[3, 6], [4, 3], [0, 8]], [[3, 1], [4, 9], [4, 0]]]
[array([[3, 6],
       [4, 3],
       [0, 8]]), array([[3, 1],
       [4, 9],
       [4, 0]])]
