In [47]:
#[簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？
import numpy as np
a = np.arange(18).reshape([6,3])
print(a)
print(type(a))
print(a.dtype)      

#請撰寫一個判斷 a 的元素是否等於指定資料型態的函式
print(a.dtype == 'int32') 
print(a.dtype is 'int32') 
print(a.dtype is np.int32) 
print(a.dtype == 'int32') 
print(a.dtype == np.int64) 
print(a.dtype is np.dtype('int32'))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
<class 'numpy.ndarray'>
int32
True
False
False
True
False
True


<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-47-154a50121568>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(a.dtype is 'int32')


In [45]:
#[簡答題] 承上題，請判斷下列三種寫法為何不正確？
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
print(a.dtype == int)
print(a.dtype is 'int')
print(a.dtype is np.dtype(int))

True
False
True


<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-45-790f03f6715d>:10: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(a.dtype is 'int')
