In [6]:
# 1. [簡答題] 請問下列程式碼，運算結果分別為何？
import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

print(a + a)  #2倍的意思
print(a + b)  #相加的意思
print(a + c)  #各+1的意思
print(a + d)  #同上
print(a + e)  #因shape不符，無法相加


[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [17]:
# 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？
#不用迴圈
import numpy as np
A = np.ones(3)*1
B = np.ones(3)*2
print(A,B)
C = (A+B)*(-A/2)
print(C)

#用迴圈
data=[]
for i in np.arange(A.size):
    data.append((A[i]+B[i])*(-A[i]/2))
print(data)
    

[1. 1. 1.] [2. 2. 2.]
[-1.5 -1.5 -1.5]
[-1.5, -1.5, -1.5]


In [7]:
# 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6]
])
print('內積',a@b)
print('外積',np.outer(a,b))

c = np.ones((1,6))
d = np.ones((6,1))
print('內積',c@d)
print('外積',np.outer(c,d))

內積 [91]
外積 [[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
內積 [[6.]]
外積 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
