In [8]:
#[簡答題] 請問下列這三種方法有什麼不同？
import numpy as np
a = np.arange(12)
print(a)
print(a.sum())
print(a.sum().dtype)
print(np.sum(a))
print(np.sum(a).dtype)
print(sum(a)) 
print(sum(a).dtype)
#答案一模一樣


[ 0  1  2  3  4  5  6  7  8  9 10 11]
66
int32
66
int32
66
int32


In [14]:
#請對一個 5x5 的隨機矩陣作正規化的操作。
import numpy as np
a = np.random.random((5, 5)) 
print(a)
# normalize到0 ~ 1的區間
a = (a - a.min()) / (a.max() - a.min())
print("\nNormalization:")
print(a)


[[0.61282317 0.4096337  0.38163002 0.17239603 0.58263454]
 [0.66481769 0.60853014 0.46002493 0.62286169 0.49437488]
 [0.21667134 0.35469789 0.57483467 0.02412391 0.27922621]
 [0.06435108 0.89782611 0.97843441 0.83749302 0.75505372]
 [0.73272683 0.84961652 0.75585081 0.70732853 0.6698137 ]]

Normalization:
[[0.6168844  0.40396683 0.37462243 0.15537094 0.58525043]
 [0.67136826 0.61238583 0.45677064 0.62740354 0.49276516]
 [0.20176601 0.34640086 0.57707713 0.         0.26731583]
 [0.04215312 0.91553242 1.         0.85231076 0.76592453]
 [0.74252869 0.8650147  0.76675977 0.71591439 0.67660347]]


In [19]:
#請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。
import numpy as np
a = np.arange(10)
print(a)
a[a.max()]=-1
#a[a.argmax()] = -1
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8 -1]


In [26]:
#1.將下列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")
import numpy as np
array1 = np.array(range(30))
array2 = array1.reshape((5, 6), order="F")
print(array1)
print(array2)

#2.呈上題的 array，找出被 6 除餘 1 的數的索引
array3 = np.where(array2%6==1)
print(array3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]
(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))
