In [ ]:
import numpy as np
import timeit

In [27]:
#請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。
import numpy as np
import timeit
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
#方法1:直接全部+1
%timeit -n 10 a = 2

Z_method1 = Z + 1

print(Z[0,0,0])
print(Z_method1[0,0,0])

The slowest run took 4.42 times longer than the fastest. This could mean that an intermediate result is being cached.
610 ns ± 448 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
6
7


In [28]:
#方法2:用falt把它攤平
%timeit -n 10 a = 2

Z_method2 = []

for i in Z.flat:
    Z_method2.append(i+1)

Z_method2_array = np.array(Z_method2, dtype = int).reshape(100,100,100)
print(Z[0,0,0])
print(Z_method2_array[0,0,0])

407 ns ± 26.6 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
6
7


In [29]:
#方法3:nditer
%timeit -n 10 a = 2

Z_method3 = []

for i in np.nditer(Z, order = 'C'):
    Z_method3.append(i+1)

Z_method3_array = np.array(Z_method3, dtype = int).reshape(100,100,100)
print(Z[0,0,0])
print(Z_method2_array[0,0,0])

319 ns ± 82.2 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
6
7


In [30]:
#如何從一個陣列中，找出出現頻率最高的數值與位置？
#2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

Z = np.random.randint(0,10,50)

Z_bincount = np.bincount(Z) # 找0~序列最大值在array中出現的次數
print(Z_bincount)
Z_index = np.argmax(Z_bincount)
Z_index
print("出現頻率最高的值為:", Z_index)

[3 2 5 8 5 5 4 6 8 4]
出現頻率最高的值為: 3


In [31]:
#如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[5, 2, 7, 4, 7, 1]
[5, 2, 7, 4, 7, 1]
[[5, 8, 1, 1], [4, 7, 9, 4], [2, 9, 9, 8]]
[array([5, 8, 1, 1]), array([4, 7, 9, 4]), array([2, 9, 9, 8])]
[[[2, 5], [9, 2], [1, 0]], [[3, 0], [4, 7], [0, 2]]]
[array([[2, 5],
       [9, 2],
       [1, 0]]), array([[3, 0],
       [4, 7],
       [0, 2]])]


In [35]:
#1運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array1_inv = np.linalg.inv(array1)
ans = array1 @ array1_inv
print(ans)

#2運用上列array計算特徵值、特徵向量?
eigen = np.linalg.eig(array1)
print("eigen value: ", eigen[0])
print("eigen vector: ", eigen[1])

#3運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)
print(u)
print(s)
print(vh)

[[1. 0.]
 [0. 1.]]
eigen value:  [13.  2.]
eigen vector:  [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]
[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
